name: VelaUX APIServer Test

on:
  push:
    branches:
      - main
      - release-*
      - master
    tags:
      - v*
  workflow_dispatch: { }
  pull_request:
    branches:
      - main
      - release-*
      - master

env:
  # Common versions
  GO_VERSION: '1.19'

permissions:
  contents: read

jobs:

  detect-noop:
    runs-on: ubuntu-20.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
        continue-on-error: true

  server-unit-tests:
    runs-on: ubuntu-20.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: true

      - name: Cache Go Dependencies
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Install ginkgo
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y golang-ginkgo-dev


      - name: Set up OpenGauss
        uses: lgj101/opengauss-action@v1.6
        with:
          GS_VERSION: 'latest'
          GS_DB: 'kubevela'
          GS_USERNAME: 'root'
          GS_PASSWORD: 'Kubevela-123'
          HOST_PORT: 15432
          CONTAINER_PORT: 5432

      - name: Run api server unit test
        run: make unit-test-server

